//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodcorner.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using foodcorner.Models;


    public partial class DeliveryTeam
    {
        private DB22Entities3 db = new DB22Entities3();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryTeam()
        {
            this.AssignOrders = new HashSet<AssignOrder>();
        }
    
        public int DelivererId { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignOrder> AssignOrders { get; set; }

        public IEnumerable<AssignOrder> doctorsspec(int spec)
        {
            var ide = db.AssignOrders.Where(p => (p.DelivererId == spec));
            return ide;
        }

    }
}
